settings:
  title: '监控 - SmallKunKun'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: status.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Home-Page # unique identifier
    name: 博客
    description:  # default=empty
    url: 'https://kunkun.eu.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: Pan
    name: 网盘
    description: 
    url: 'https://pan.kunkun.eu.org/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Start
    name: 起始
    url: 'https://search.kunkun.eu.org/'
    method: GET
    expectStatus: 200
